### ISSUE TITLE
Missing ignore for GREASE values in ja3 digest

### ISSUE THREAD

**Issue by kjelle** [dreadl0ck/ja3#3]
Hello!

JA3 are to ignore values utilizing GREASE (https://tools.ietf.org/html/draft-davidben-tls-grease-01).

As given by https://github.com/salesforce/ja3/blob/master/python/ja3.py all values: ciphers, extensions, elliptic curve and elliptic curve point formats, should be filtered so GREASE values are not added to the ja3 digest. The ja3 authors probably did not mean to filter ecpf in GREASE since its a uint8.

Example on how this is done can be found here:
https://github.com/D4-project/sensor-d4-tls-fingerprinting
(Tho, that library is missing filtering GREASE for elliptic curves, see https://github.com/D4-project/sensor-d4-tls-fingerprinting/issues/13)

If this is not done you will not produce the correct hash.

Cheers,
Kjell Tore Fossbakk

**Comment by dreadl0ck** [comment]
Hi there! 

Thanks for the heads up - totally missed that.

Fixed with #f48187c.

I've also extended the tests to compare the output from running the reference implementation on a test pcap file, with the output generated by goja3.

I guess I owe you a beer! Let me know if you're in Amsterdam :)

Cheers,
Philipp
